version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
